# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: workflow_2

on:
  push:
    branches:
      - main

jobs:
  job_two:
    name: Run Second Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Second Task
        run: echo "This is the second job"
